# Basic url to add the local language in every url on this site. #
altitude_core:
    resource: "@AltitudeCoreBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: en|fr
        