# ----- Urls related to AltitudeCoreBundle ----- #
altitude_core_homepage:
    path:     /
    defaults: { _controller: AltitudeCoreBundle:Core:index }

altitude_core_index:
    path:     /home
    defaults: { _controller: AltitudeCoreBundle:Core:index }

# ----- Urls related to Other bundles ----- #
altitude_blog:
    resource: "@AltitudeBlogBundle/Resources/config/routing.yml"
    prefix:   /blog
    requirements:
        _locale: en|fr

# ----- Urls related to FOSUserBundle ----- #
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

altitude_user_login_success:
    path:     /
    defaults: { _controller: AltitudeUserBundle:UserSecurity:loginSuccess }

altitude_user_logout_success:
    path:     /
    defaults: { _controller: AltitudeUserBundle:UserSecurity:logoutSuccess }
